service: pintweet

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  - ${file(./main.yml)}
  - ${file(./user/user.lambda.yml)}
  - ${file(./tweet/tweet.lambda.yml)}

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 3000
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
