service: tweet-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  - ${file(./tweet.lambda.yml)}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4002
    lambdaPort: 3002
