service: user-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: localhost

functions:
  - ${file(./user.lambda.yml)}

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  serverless-offline:
    httpPort: 4001
    lambdaPort: 3001
