service: user-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  - ${file(./user.lambda.yml)}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4001
    lambdaPort: 3001
